solids:
  create_dataframe:
    inputs:
      csv_path:
        value: "data/raw/comments_train.csv"
  grid_search_random_forest:
    inputs:
      param_grid:
        value: {'n_estimators': [5, 10,20],
                'max_features': ['auto', 'sqrt', 'log2'],
                'max_depth' : [4,5,6,7,8],
                'criterion' :['gini', 'entropy']}
  grid_search_logistic_regression:
    inputs:
      param_grid:
        value: {"C":np.logspace(-3,3,7), 
                "penalty":["l2", "elasticnet", "none"],
                "class_weight": ["balanced", "None"]}

