solids:
  create_dataframe:
    inputs:
      csv_path:
        value: "data/raw/comments_train.csv"
  grid_search_random_forest:
    inputs:
      key:
        value: 'rf'
      param_grid:
        value: {"n_estimators": [5, 10],
                "max_features": ["auto"],
                "max_depth" : [1,2]}
  grid_search_logistic_regression:
    inputs:
      key:
        value: 'reg'
      param_grid:
        value: {"penalty":["l2", "elasticnet", "none"],
                "class_weight": ["balanced", "None"]}

